# Generated by Django 2.2.3 on 2019-07-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
