# Generated by Django 2.2.3 on 2019-07-10 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_nutrition',
        ),
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='approval.Unit'),
            preserve_default=False,
        ),
    ]
