# Generated by Django 2.2.3 on 2019-07-08 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='approval.UserGroup'),
        ),
    ]
