# Generated by Django 2.2.3 on 2019-07-09 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0006_auto_20190709_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='nutrition', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_category',
        ),
        migrations.AddField(
            model_name='user',
            name='is_nutrition',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
