# Generated by Django 2.2.3 on 2019-07-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0009_auto_20190711_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('tech', 'Technical Review'), ('prc_review', 'PRC Review'), ('prc_meeting', 'PRC Meeting'), ('nfr', 'NFR Created'), ('closed', 'Closed')], default='tech', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('tech', 'Technical Review'), ('prc_review', 'PRC Review'), ('prc_meeting', 'PRC Meeting'), ('nfr', 'NFR Created'), ('closed', 'Closed')], default='tech', max_length=50),
        ),
    ]
