# Generated by Django 2.2.3 on 2019-07-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0011_comment_add_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
    ]
