# Generated by Django 2.2.3 on 2019-07-12 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0012_auto_20190712_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_text',
        ),
    ]
