# Generated by Django 2.2.3 on 2019-07-13 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0013_auto_20190712_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.Unit'),
        ),
    ]
