# Generated by Django 2.2.3 on 2019-07-14 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0015_auto_20190713_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='approval.Unit'),
        ),
    ]
